service: sportligthApp #Name of your App
provider:
  name: aws
  runtime: nodejs20.x # Node JS version
  memorySize: 512
  timeout: 30
  stage: dev 
  region: ca-central-1 # AWS region
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
